### ISSUE TITLE
BlipTV videos fail to load

### ISSUE THREAD

**Issue by sakuramboo** [dethfeet/plugin.video.retrowaretv#2]
08:35:29 T:2692428896  NOTICE: http://retrowaretv.com/lets-get-licensed-nes-zapper-games-part-4-laser-invasion/
08:35:30 T:2692428896  NOTICE: http://blip.tv/play/AYOc7ggA.x?p=1
08:35:30 T:2692428896 WARNING: Attempt to use invalid handle 12
08:35:30 T:2777330784  NOTICE: Thread XBPyThread start, auto delete: false
08:35:31 T:2777330784  NOTICE: -->Python Interpreter Initialized<--
08:35:31 T:2777330784  NOTICE: BlipTV-1.8.3
08:35:33 T:2777330784  NOTICE: CommonFunctions-2.5.1
08:35:34 T:2777330784   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('content',)
                                            Traceback (most recent call last):
                                              File "/storage/.xbmc/addons/plugin.video.bliptv/default.py", line 86, in <module>
                                                navigation.executeAction(params)
                                              File "/storage/.xbmc/addons/plugin.video.bliptv/BlipTVNavigation.py", line 134, in executeAction
                                                self.player.playVideo(params)
                                              File "/storage/.xbmc/addons/plugin.video.bliptv/BlipTVPlayer.py", line 46, in playVideo
                                                video = self.getVideoObject(params)
                                              File "/storage/.xbmc/addons/plugin.video.bliptv/BlipTVPlayer.py", line 156, in getVideoObject
                                                video = self.getInfo(result, params)
                                              File "/storage/.xbmc/addons/plugin.video.bliptv/BlipTVPlayer.py", line 74, in getInfo
                                                params["apierror"] = result["content"]
                                            KeyError: ('content',)
                                            -->End of Python script error report<--
08:35:34 T:3046780928   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.retrowaretv/?action=playEpisode&link=http%3A%2F%2Fretrowaretv.
com%2Flets-get-licensed-nes-zapper-games-part-4-laser-invasion%2F]

**Comment by sakuramboo** [comment]
It seems that the Blip.TV addon made by TheCollective is no longer maintained.

I tried the addon from addonscriptorde-beta-repo but now it doesn't even error out. It just doesn't load.
